import { existsSync } from "node:fs";
import path from "node:path";
import { ensureImage, inContainer } from "../docker.js";
import type { Finding, RunContext, StageResult } from "../types.js";

/**
 * Coverage-guided stateful fuzzing with Medusa, on a suite with a medusa.json at the project root
 * (for example one generated by the fizz skill). Runs in the Docker sandbox.
 */
export async function medusa(ctx: RunContext): Promise<StageResult> {
  if (!existsSync(path.join(ctx.workDir, "medusa.json"))) {
    return { name: "medusa", status: "skipped", durationMs: 0, summary: "No medusa.json; generate a suite (e.g. with the fizz skill) and add it via --harness", findings: [], log: "" };
  }
  const image = await ensureImage();
  if (!image.ok) {
    return { name: "medusa", status: "failed", durationMs: 0, summary: "Could not build the Docker tools image", findings: [], log: image.log };
  }

  const r = await inContainer(ctx, `medusa fuzz --timeout ${ctx.medusaSeconds} 2>&1 || true`, (ctx.medusaSeconds + 600) * 1000);
  const out = (r.stdout + r.stderr).replace(/\x1b\[[0-9;]*m/g, "");
  const failed = [...out.matchAll(/\[FAILED\]\s+(.+)/g)].map((m) => m[1].trim());
  const summaryLine = out.match(/Test summary:.*$/m)?.[0];

  const findings: Finding[] = [...new Set(failed)].map((t, i) => ({
    tool: "medusa",
    id: `medusa-${i + 1}`,
    title: `Medusa property failed: ${t}`,
    severity: "high",
    confidence: "high",
    locations: [],
    description: `Medusa broke this property; the shrunk call sequence is in logs/medusa.log.`,
  }));
  return {
    name: "medusa",
    status: summaryLine ? "ok" : "failed",
    durationMs: r.durationMs,
    summary: summaryLine ?? "Medusa produced no test summary",
    findings,
    log: out,
  };
}
